//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schools_tbl
    {
        public int school_id { get; set; }
        public string school_descr { get; set; }
        public string school_type { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
